# Funding

dao: 0x83E2403A8b94AF988B4F4Ae9869577783b8CD216 (Optimism)



# Gov is developed and maintained by the Web3 Hackers Collective ([W3HC](https://github.com/w3hc)). If you want to support its development, please send some funds (ERC-20 or ETH) to our DAO on Optimism. 

# [0x83E2403A8b94AF988B4F4Ae9869577783b8CD216](https://www.tally.xyz/gov/web3-hackers-collective) on Optimism Mainnet
